export const en = {
  common: {
    appName: 'CodeMate',
    tagline: 'Create. Scan. Share. Everywhere.',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    share: 'Share',
    save: 'Save',
    download: 'Download',
    copy: 'Copy Value',
    seeAll: 'See All',
    loading: 'Loading...',
    success: 'Success',
    error: 'Something went wrong',
    active: 'Active',
    expiresToday: 'Expires Today',
    expired: 'Expired',
    qr: 'QR Code',
    barcode: 'Barcode',
    generated: 'Generated',
    scanned: 'Scanned',
    getStarted: 'Get Started',
    next: 'Next',
    skip: 'Skip',
    createNew: 'Create New',
    scanAgain: 'Scan Again',
    regenerate: 'Regenerate',
    saveToGallery: 'Save to Gallery',
    openSettings: 'Open Settings',
    grantPermission: 'Grant Permission',
    unableOpenLink: 'Unable to open this link.',
  },
  tabs: {
    home: 'Home',
    history: 'History',
    scan: 'Scan',
    settings: 'Settings',
  },
  home: {
    greeting: 'Hello, {{name}}',
    subtitle: 'What would you like to do today?',
    generateQr: 'Generate QR Code',
    generateBarcode: 'Generate Barcode',
    scanCode: 'Scan Code',
    scanDescription: 'Scan QR codes or barcodes instantly.',
    recentCodes: 'Recent Codes',
    emptyTitle: 'No codes yet',
    emptySubtitle: 'Generate or scan a code and it will appear here.',
  },
  onboarding: {
    page1Title: 'Generate',
    page1Body: 'Create QR codes and barcodes in seconds.',
    page2Title: 'Scan',
    page2Body: 'Scan QR codes and barcodes instantly.',
    page3Title: 'Share',
    page3Body: 'Save or share your codes anywhere.',
  },
  nav: {
    generateQr: 'Generate QR',
    generateBarcode: 'Generate Barcode',
    qrPreview: 'QR Preview',
    barcodePreview: 'Barcode Preview',
    details: 'Details',
    scanResult: 'Scan Result',
  },
  generate: {
    qrTitle: 'Generate QR Code',
    barcodeTitle: 'Generate Barcode',
    name: 'Name',
    englishName: 'Name (English)',
    urduName: 'نام (اردو)',
    price: 'Price',
    createdDate: 'Date of Creation',
    expiryDate: 'Date of Expiry',
    generateQrCta: 'Generate QR Code',
    generateBarcodeCta: 'Generate Barcode',
    successQr: 'QR code generated successfully.',
    successBarcode: 'Barcode generated successfully.',
  },
  preview: {
    qrTitle: 'Your QR Code',
    barcodeTitle: 'Your Barcode',
    name: 'Name',
    urduName: 'Urdu Name',
    price: 'Price',
    created: 'Created',
    expiry: 'Expiry',
    savedGallery: 'Saved to your gallery.',
    unableSave: 'Unable to save image.',
    unableShare: 'Unable to share code.',
  },
  scanner: {
    title: 'Scan Code',
    subtitle: 'QR codes & barcodes',
    align: 'Align the code inside the frame',
    hintDetail: 'Hold steady — scanning happens automatically',
    notDetected: 'QR code or barcode not detected',
    detected: 'Code detected',
    viewDetails: 'View details',
    permissionTitle: 'Camera Permission Required',
    permissionBody:
      'CodeMate needs access to your camera to scan QR codes and barcodes.',
    unavailable: 'Unable to access camera.',
    success: 'Code scanned successfully!',
    flashOn: 'Flash on',
    flashOff: 'Flash off',
  },
  scanResult: {
    title: 'Scan Result',
    productInformation: 'Product Information',
    scannedCode: 'Scanned Code',
    type: 'Type',
    rawValue: 'Raw Value',
    copied: 'Value copied.',
    savedHint: 'This code has been saved to your history.',
  },
  history: {
    title: 'History',
    search: 'Search codes',
    all: 'All',
    generated: 'Generated',
    scanned: 'Scanned',
    qr: 'QR',
    barcode: 'Barcode',
    today: 'Today',
    yesterday: 'Yesterday',
    emptyTitle: 'No history yet',
    emptySubtitle: 'Your generated and scanned codes will show up here.',
    clearConfirmTitle: 'Clear all history?',
    clearConfirmBody: 'This will permanently delete every saved code.',
    deleteConfirmTitle: 'Delete this code?',
    deleteConfirmBody: 'This action cannot be undone.',
    filterBySource: 'Source',
    filterByType: 'Type',
    recordCount_one: '{{count}} record',
    recordCount_other: '{{count}} records',
  },
  details: {
    title: 'Code Details',
    status: 'Status',
    source: 'Source',
  },
  settings: {
    title: 'Settings',
    general: 'General',
    language: 'Language',
    appearance: 'Appearance',
    system: 'System',
    light: 'Light',
    dark: 'Dark',
    data: 'Data',
    forms: 'Forms',
    clearHistory: 'Clear History',
    permissions: 'Permissions',
    cameraPermission: 'Camera Permission',
    about: 'About',
    version: 'Version',
    displayName: 'Display Name',
    granted: 'Granted',
    denied: 'Denied',
    notDetermined: 'Not Determined',
    restartRequiredTitle: 'Restart required',
    restartRequiredBody:
      'CodeMate needs to restart to apply the layout direction.',
    restartNow: 'Restart',
  },
  templates: {
    title: 'Form Templates',
    editTitle: 'Edit Template',
    subtitle: 'Build reusable forms for QR and barcode generation.',
    create: 'Create Template',
    newTemplate: 'New Template',
    emptyTitle: 'No templates yet',
    emptySubtitle: 'Create a template to add custom fields when generating codes.',
    default: 'Default',
    fieldCount_one: '{{count}} custom field',
    fieldCount_other: '{{count}} custom fields',
    deleteTitle: 'Delete template?',
    deleteBody: 'Delete “{{name}}”? This cannot be undone.',
    keepOne: 'Keep at least one template.',
    notFound: 'Template not found.',
    templateName: 'Template Name',
    customFields: 'Custom Fields',
    coreFieldsHint: 'Name and Expiry are always included automatically.',
    addField: 'Add Field',
    fieldLabel: 'Field Label',
    fieldLabelPlaceholder: 'e.g. Batch No',
    fieldType: 'Field Type',
    fieldLabelRequired: 'Enter a field label.',
    required: 'Required',
    useTemplate: 'Form Template',
    requiredFieldsMissing: 'Please fill: {{fields}}',
    type: {
      text: 'Text',
      date: 'Date',
      number: 'Number',
    },
  },
};
