export const en = {
  common: {
    appName: 'CodeMate',
    tagline: 'Create. Scan. Share. Everywhere.',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    share: 'Share',
    save: 'Save',
    download: 'Download',
    copy: 'Copy Value',
    seeAll: 'See All',
    loading: 'Loading...',
    success: 'Success',
    error: 'Something went wrong',
    active: 'Active',
    expiresToday: 'Expires Today',
    expired: 'Expired',
    qr: 'QR Code',
    barcode: 'Barcode',
    generated: 'Generated',
    scanned: 'Scanned',
    getStarted: 'Get Started',
    next: 'Next',
    skip: 'Skip',
    createNew: 'Create New',
    scanAgain: 'Scan Again',
    regenerate: 'Regenerate',
    saveToGallery: 'Save to Gallery',
    openSettings: 'Open Settings',
    grantPermission: 'Grant Permission',
  },
  tabs: {
    home: 'Home',
    history: 'History',
    scan: 'Scan',
    settings: 'Settings',
  },
  home: {
    greeting: 'Hello, {{name}}',
    subtitle: 'What would you like to do today?',
    generateQr: 'Generate QR Code',
    generateBarcode: 'Generate Barcode',
    scanCode: 'Scan Code',
    scanDescription: 'Scan QR codes or barcodes instantly.',
    recentCodes: 'Recent Codes',
    emptyTitle: 'No codes yet',
    emptySubtitle: 'Generate or scan a code and it will appear here.',
  },
  onboarding: {
    page1Title: 'Generate',
    page1Body: 'Create QR codes and barcodes in seconds.',
    page2Title: 'Scan',
    page2Body: 'Scan QR codes and barcodes instantly.',
    page3Title: 'Share',
    page3Body: 'Save or share your codes anywhere.',
  },
  generate: {
    qrTitle: 'Generate QR Code',
    barcodeTitle: 'Generate Barcode',
    englishName: 'Name (English)',
    urduName: 'نام (اردو)',
    price: 'Price',
    createdDate: 'Date of Creation',
    expiryDate: 'Date of Expiry',
    generateQrCta: 'Generate QR Code',
    generateBarcodeCta: 'Generate Barcode',
    successQr: 'QR code generated successfully.',
    successBarcode: 'Barcode generated successfully.',
  },
  preview: {
    qrTitle: 'Your QR Code',
    barcodeTitle: 'Your Barcode',
    name: 'Name',
    urduName: 'Urdu Name',
    price: 'Price',
    created: 'Created',
    expiry: 'Expiry',
    savedGallery: 'Saved to your gallery.',
    unableSave: 'Unable to save image.',
    unableShare: 'Unable to share code.',
  },
  scanner: {
    title: 'Scan Code',
    align: 'Align the QR code or barcode within the frame',
    permissionTitle: 'Camera Permission Required',
    permissionBody:
      'CodeMate needs access to your camera to scan QR codes and barcodes.',
    unavailable: 'Unable to access camera.',
    success: 'Code scanned successfully!',
  },
  scanResult: {
    title: 'Scan Result',
    productInformation: 'Product Information',
    scannedCode: 'Scanned Code',
    type: 'Type',
    rawValue: 'Raw Value',
    copied: 'Value copied.',
  },
  history: {
    title: 'History',
    search: 'Search codes',
    all: 'All',
    generated: 'Generated',
    scanned: 'Scanned',
    qr: 'QR',
    barcode: 'Barcode',
    emptyTitle: 'No history yet',
    emptySubtitle: 'Your generated and scanned codes will show up here.',
    clearConfirmTitle: 'Clear all history?',
    clearConfirmBody: 'This will permanently delete every saved code.',
    deleteConfirmTitle: 'Delete this code?',
    deleteConfirmBody: 'This action cannot be undone.',
  },
  details: {
    title: 'Code Details',
    status: 'Status',
    source: 'Source',
  },
  settings: {
    title: 'Settings',
    general: 'General',
    language: 'Language',
    appearance: 'Appearance',
    system: 'System',
    light: 'Light',
    dark: 'Dark',
    data: 'Data',
    clearHistory: 'Clear History',
    permissions: 'Permissions',
    cameraPermission: 'Camera Permission',
    about: 'About',
    version: 'Version',
    displayName: 'Display Name',
    granted: 'Granted',
    denied: 'Denied',
    notDetermined: 'Not Determined',
  },
};
