export const ur = {
  common: {
    appName: 'کوڈ میٹ',
    tagline: 'بنائیں۔ اسکین کریں۔ شیئر کریں۔ ہر جگہ۔',
    cancel: 'منسوخ',
    confirm: 'تصدیق',
    delete: 'حذف',
    share: 'شیئر',
    save: 'محفوظ',
    download: 'ڈاؤن لوڈ',
    copy: 'ویلیو کاپی کریں',
    seeAll: 'سب دیکھیں',
    loading: 'لوڈ ہو رہا ہے...',
    success: 'کامیاب',
    error: 'کچھ غلط ہو گیا',
    active: 'فعال',
    expiresToday: 'آج ختم',
    expired: 'میعاد ختم',
    qr: 'کیو آر کوڈ',
    barcode: 'بارکوڈ',
    generated: 'تیار کردہ',
    scanned: 'اسکین شدہ',
    getStarted: 'شروع کریں',
    next: 'آگے',
    skip: 'چھوڑیں',
    createNew: 'نیا بنائیں',
    scanAgain: 'دوبارہ اسکین',
    regenerate: 'دوبارہ بنائیں',
    saveToGallery: 'گیلری میں محفوظ کریں',
    openSettings: 'سیٹنگز کھولیں',
    grantPermission: 'اجازت دیں',
  },
  tabs: {
    home: 'ہوم',
    history: 'ہسٹری',
    scan: 'اسکین',
    settings: 'سیٹنگز',
  },
  home: {
    greeting: 'السلام علیکم، {{name}}',
    subtitle: 'آج آپ کیا کرنا چاہتے ہیں؟',
    generateQr: 'کیو آر کوڈ بنائیں',
    generateBarcode: 'بارکوڈ بنائیں',
    scanCode: 'کوڈ اسکین کریں',
    scanDescription: 'فوری طور پر کیو آر یا بارکوڈ اسکین کریں۔',
    recentCodes: 'حالیہ کوڈز',
    emptyTitle: 'ابھی کوئی کوڈ نہیں',
    emptySubtitle: 'کوڈ بنائیں یا اسکین کریں، یہاں نظر آئے گا۔',
  },
  onboarding: {
    page1Title: 'بنائیں',
    page1Body: 'سیکنڈوں میں کیو آر اور بارکوڈ تیار کریں۔',
    page2Title: 'اسکین',
    page2Body: 'فوری طور پر کیو آر اور بارکوڈ اسکین کریں۔',
    page3Title: 'شیئر',
    page3Body: 'اپنے کوڈز کہیں بھی محفوظ یا شیئر کریں۔',
  },
  nav: {
    generateQr: 'کیو آر بنائیں',
    generateBarcode: 'بارکوڈ بنائیں',
    qrPreview: 'کیو آر پیش نظارہ',
    barcodePreview: 'بارکوڈ پیش نظارہ',
    details: 'تفصیلات',
    scanResult: 'اسکین نتیجہ',
  },
  generate: {
    qrTitle: 'کیو آر کوڈ بنائیں',
    barcodeTitle: 'بارکوڈ بنائیں',
    name: 'نام',
    englishName: 'نام (انگریزی)',
    urduName: 'نام (اردو)',
    price: 'قیمت',
    createdDate: 'تخلیق کی تاریخ',
    expiryDate: 'میعاد ختم ہونے کی تاریخ',
    generateQrCta: 'کیو آر کوڈ بنائیں',
    generateBarcodeCta: 'بارکوڈ بنائیں',
    successQr: 'کیو آر کوڈ کامیابی سے بن گیا۔',
    successBarcode: 'بارکوڈ کامیابی سے بن گیا۔',
  },
  preview: {
    qrTitle: 'آپ کا کیو آر کوڈ',
    barcodeTitle: 'آپ کا بارکوڈ',
    name: 'نام',
    urduName: 'اردو نام',
    price: 'قیمت',
    created: 'بنایا گیا',
    expiry: 'میعاد',
    savedGallery: 'گیلری میں محفوظ ہو گیا۔',
    unableSave: 'تصویر محفوظ نہیں ہو سکی۔',
    unableShare: 'شیئر نہیں ہو سکا۔',
  },
  scanner: {
    title: 'کوڈ اسکین کریں',
    subtitle: 'کیو آر اور بارکوڈ',
    align: 'کوڈ کو فریم کے اندر رکھیں',
    hintDetail: 'Steady رکھیں — اسکین خود بخود ہوگا',
    notDetected: 'کیو آر یا بارکوڈ نہیں ملا',
    detected: 'کوڈ مل گیا',
    viewDetails: 'تفصیلات دیکھیں',
    permissionTitle: 'کیمرہ اجازت درکار ہے',
    permissionBody:
      'کوڈ میٹ کو کیو آر اور بارکوڈ اسکین کرنے کے لیے کیمرہ چاہیے۔',
    unavailable: 'کیمرہ دستیاب نہیں۔',
    success: 'کوڈ کامیابی سے اسکین ہو گیا!',
    flashOn: 'فلیش آن',
    flashOff: 'فلیش آف',
  },
  scanResult: {
    title: 'اسکین نتیجہ',
    productInformation: 'مصنوعات کی معلومات',
    scannedCode: 'اسکین شدہ کوڈ',
    type: 'قسم',
    rawValue: 'اصل ویلیو',
    copied: 'ویلیو کاپی ہو گئی۔',
    savedHint: 'یہ کوڈ آپ کی ہسٹری میں محفوظ ہو گیا ہے۔',
  },
  history: {
    title: 'ہسٹری',
    search: 'کوڈز تلاش کریں',
    all: 'سب',
    generated: 'تیار کردہ',
    scanned: 'اسکین شدہ',
    qr: 'کیو آر',
    barcode: 'بارکوڈ',
    today: 'آج',
    yesterday: 'کل',
    emptyTitle: 'ابھی ہسٹری نہیں',
    emptySubtitle: 'تیار اور اسکین شدہ کوڈز یہاں نظر آئیں گے۔',
    clearConfirmTitle: 'ساری ہسٹری صاف کریں؟',
    clearConfirmBody: 'تمام محفوظ کوڈز مستقل طور پر حذف ہو جائیں گے۔',
    deleteConfirmTitle: 'یہ کوڈ حذف کریں؟',
    deleteConfirmBody: 'یہ عمل واپس نہیں ہو سکتا۔',
    filterBySource: 'ذریعہ',
    filterByType: 'قسم',
    recordCount_one: '{{count}} ریکارڈ',
    recordCount_other: '{{count}} ریکارڈز',
  },
  details: {
    title: 'کوڈ کی تفصیل',
    status: 'حیثیت',
    source: 'ذریعہ',
  },
  settings: {
    title: 'سیٹنگز',
    general: 'عام',
    language: 'زبان',
    appearance: 'ظاہری شکل',
    system: 'سسٹم',
    light: 'لائٹ',
    dark: 'ڈارک',
    data: 'ڈیٹا',
    clearHistory: 'ہسٹری صاف کریں',
    permissions: 'اجازتیں',
    cameraPermission: 'کیمرہ اجازت',
    about: 'تعارف',
    version: 'ورژن',
    displayName: 'ڈسپلے نام',
    granted: 'دی گئی',
    denied: 'مسترد',
    notDetermined: 'غیر طے شدہ',
    restartRequiredTitle: 'ری سٹارٹ درکار ہے',
    restartRequiredBody:
      'لے آؤٹ کی سمت لاگو کرنے کے لیے کوڈ میٹ کو دوبارہ شروع کرنا ہوگا۔',
    restartNow: 'ری سٹارٹ',
  },
};
